
name: formsflow-forms

on:
  push:
    branches: [ formsflow-forms ]
  pull_request:
    branches: [ formsflow-forms, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    services:
      mongodb:
        image: mongo:5
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Run tests
      run: npm test
      env:
        ROOT_EMAIL: admin@example.com
        ROOT_PASSWORD: Changeme1!
